name: e_commerce_mobile
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
 # package for sliding the images
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  # An efficient way to for object equality
  equatable: ^2.0.5
  # Firebase
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0

  flutter:
    sdk: flutter

  # Hooks
  flutter_hooks: ^0.18.6

  # package for responsiveness
  flutter_screenutil: ^5.6.1

  # This library will be responsible for localization in the project.
  intl: ^0.17.0
  stacked: ^3.1.0+3
  stacked_firebase_auth: ^0.2.18
  stacked_services: ^0.9.9

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.9.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/background/shopping.jpg
    - assets/images/background/cart.png
    - assets/images/person/maleA.jpeg
    - assets/images/person/maleB.jpg
    - assets/images/person/femaleA.jpg
    - assets/images/person/c1.jpg
    - assets/images/person/w1.jpeg
    - assets/images/person/w3.jpeg
    - assets/images/person/w4.jpeg
    - assets/images/person/back.jpg
    - assets/images/person/maleC.jpg
    - assets/images/person/maleD.jpg
    - assets/images/person/maleE.jpg
    - assets/images/items/tshirt.png
    - assets/images/items/accessories.png
    - assets/images/items/shoe.png
    - assets/images/items/jeans.png
    - assets/images/items/formal.png
    - assets/images/items/informal.png
    - assets/images/items/dress.png
    - assets/images/products/blazer1.jpeg
    - assets/images/products/blazer2.jpeg
    - assets/images/products/dress1.jpeg
    - assets/images/products/dress2.jpeg
    - assets/images/products/hills1.jpeg
    - assets/images/products/hills2.jpeg
    - assets/images/products/pants2.jpeg
    - assets/images/products/skt1.jpeg
    - assets/images/products/skt2.jpeg

    
    - assets/fonts/
  
 
  fonts:
    - family: SecularOne
      fonts:
        - asset: assets/fonts/SecularOne-Regular.ttf
  

  
