name: e_commerce_mobile
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  # An efficient way to for object equality
  equatable: ^2.0.5
  # Firebase
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0

  flutter:
    sdk: flutter

  # Hooks
  flutter_hooks: ^0.18.6

  # package for responsiveness
  flutter_screenutil: ^5.6.1

  # This library will be responsible for localization in the project.
  intl: ^0.17.0
  stacked: ^3.1.0+3
  stacked_firebase_auth: ^0.2.18
  stacked_services: ^0.9.9

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.9.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
 
  fonts:
    - family: SecularOne
      fonts:
        - asset: fonts/SecularOne-Regular.ttf
  

  
